import Foundation
import SwiftUI

final class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    @Published var currentLanguage: String {
        didSet {
            UserDefaults.standard.set(currentLanguage, forKey: "mq_language")
            loadStrings()
        }
    }

    private var strings: [String: String] = [:]

    static let supportedLanguages = [
        "ru": "Русский",
        "en": "English",
    ]

    private let ru: [String: String] = [
        "app_name": "MQ",
        "home": "Главная",
        "chats": "Чаты",
        "notifications": "Уведомления",
        "profile": "Профиль",
        "settings": "Настройки",
        "login": "Вход",
        "phone_number": "Номер телефона",
        "enter_phone": "Введите номер телефона",
        "continue": "Продолжить",
        "verification": "Подтверждение",
        "enter_code": "Введите код",
        "verify": "Подтвердить",
        "demo_hint": "Введите любой номер для демо-входа",
        "search": "Поиск",
        "search_users": "Поиск пользователей",
        "search_messages": "Поиск сообщений",
        "new_chat": "Новый чат",
        "new_group": "Новая группа",
        "new_channel": "Новый канал",
        "create": "Создать",
        "cancel": "Отмена",
        "done": "Готово",
        "delete": "Удалить",
        "edit": "Редактировать",
        "reply": "Ответить",
        "forward": "Переслать",
        "copy": "Копировать",
        "pin": "Закрепить",
        "unpin": "Открепить",
        "mute": "Выключить звук",
        "unmute": "Включить звук",
        "star": "В избранное",
        "unstar": "Убрать из избранного",
        "block": "Заблокировать",
        "unblock": "Разблокировать",
        "report": "Пожаловаться",
        "leave_group": "Покинуть группу",
        "delete_chat": "Удалить чат",
        "group_name": "Название группы",
        "channel_name": "Название канала",
        "description": "Описание",
        "members": "Участники",
        "add_members": "Добавить участников",
        "admin": "Администратор",
        "owner": "Владелец",
        "member": "Участник",
        "invite_link": "Ссылка-приглашение",
        "message_placeholder": "Сообщение...",
        "typing": "печатает...",
        "online": "в сети",
        "offline": "не в сети",
        "last_seen": "был(а)",
        "today": "Сегодня",
        "yesterday": "Вчера",
        "read": "Прочитано",
        "delivered": "Доставлено",
        "sent": "Отправлено",
        "edited": "ред.",
        "deleted_message": "Сообщение удалено",
        "photo": "Фото",
        "video": "Видео",
        "audio": "Аудио",
        "file": "Файл",
        "attach": "Прикрепить",
        "saved_messages": "Избранное",
        "camera": "Камера",
        "location": "Локация",
        "contact": "Контакт",
        "poll": "Опрос",
        "voice_message": "Голосовое сообщение",
        "username": "Имя пользователя",
        "display_name": "Отображаемое имя",
        "bio": "О себе",
        "phone": "Телефон",
        "edit_profile": "Редактировать профиль",
        "change_avatar": "Изменить фото",
        "privacy_security": "Приватность",
        "confidentiality": "Конфиденциальность",
        "chat_appearance": "Оформление чатов",
        "notification_settings": "Уведомления",
        "language": "Язык",
        "data_storage": "Данные и хранилище",
        "help": "Помощь",
        "about": "О приложении",
        "logout": "Выйти",
        "show_online_status": "Показывать онлайн-статус",
        "show_last_seen": "Показывать время посещения",
        "read_receipts": "Отчёты о прочтении",
        "show_typing": "Индикатор набора",
        "two_step_verification": "Двухэтапная проверка",
        "enable": "Включить",
        "disable": "Выключить",
        "blocked_users": "Заблокированные",
        "active_sessions": "Активные сессии",
        "theme": "Тема",
        "light": "Светлая",
        "dark": "Тёмная",
        "system": "Системная",
        "wallpaper": "Обои чата",
        "font_size": "Размер шрифта",
        "message_corners": "Скругление сообщений",
        "bubble_color": "Цвет сообщений",
        "notification_sound": "Звук уведомления",
        "vibration": "Вибрация",
        "message_preview": "Предпросмотр",
        "in_app_notifications": "Уведомления в приложении",
        "contacts": "Контакты",
        "add_contact": "Добавить контакт",
        "favorites": "Избранное",
        "no_chats": "Нет чатов",
        "no_notifications": "Нет уведомлений",
        "no_contacts": "Нет контактов",
        "no_results": "Нет результатов",
        "loading": "Загрузка...",
        "error": "Ошибка",
        "retry": "Повторить",
        "select_members": "Выберите участников",
        "group_created": "Группа создана",
        "channel_created": "Канал создан",
        "message_deleted": "Сообщение удалено",
        "copied": "Скопировано",
        "pinned": "Закреплено",
        "welcome": "Добро пожаловать в MQ!",
        "welcome_subtitle": "Быстрый и безопасный мессенджер",
        "calls": "Звонки",
        "voice_call": "Голосовой звонок",
        "video_call": "Видеозвонок",
        "end_call": "Завершить",
        "stories": "Истории",
        "pin_code": "PIN-код",
        "enter_pin": "Введите PIN-код",
        "confirm_pin": "Подтвердите PIN",
        "clear_chat": "Очистить чат",
        "auto_delete": "Автоудаление",
        "encryption": "Шифрование",
        "e2e_encrypted": "Сквозное шифрование",
        "fingerprint_lock": "Блокировка по отпечатку",
        "public_group": "Публичная группа",
        "private_group": "Закрытая группа",
        "slow_mode": "Медленный режим",
        "permissions": "Разрешения",
        "send_media": "Отправка медиа",
        "version": "Версия",
    ]

    private let en: [String: String] = [
        "app_name": "MQ",
        "home": "Home",
        "chats": "Chats",
        "notifications": "Notifications",
        "profile": "Profile",
        "settings": "Settings",
        "login": "Login",
        "phone_number": "Phone Number",
        "enter_phone": "Enter phone number",
        "continue": "Continue",
        "verification": "Verification",
        "enter_code": "Enter code",
        "verify": "Verify",
        "demo_hint": "Enter any number for demo login",
        "search": "Search",
        "search_users": "Search users",
        "search_messages": "Search messages",
        "new_chat": "New Chat",
        "new_group": "New Group",
        "new_channel": "New Channel",
        "create": "Create",
        "cancel": "Cancel",
        "done": "Done",
        "delete": "Delete",
        "edit": "Edit",
        "reply": "Reply",
        "forward": "Forward",
        "copy": "Copy",
        "pin": "Pin",
        "unpin": "Unpin",
        "mute": "Mute",
        "unmute": "Unmute",
        "star": "Star",
        "unstar": "Unstar",
        "block": "Block",
        "unblock": "Unblock",
        "report": "Report",
        "leave_group": "Leave Group",
        "delete_chat": "Delete Chat",
        "group_name": "Group Name",
        "channel_name": "Channel Name",
        "description": "Description",
        "members": "Members",
        "add_members": "Add Members",
        "admin": "Admin",
        "owner": "Owner",
        "member": "Member",
        "invite_link": "Invite Link",
        "message_placeholder": "Message...",
        "typing": "typing...",
        "online": "online",
        "offline": "offline",
        "last_seen": "last seen",
        "today": "Today",
        "yesterday": "Yesterday",
        "read": "Read",
        "delivered": "Delivered",
        "sent": "Sent",
        "edited": "edited",
        "deleted_message": "Message deleted",
        "photo": "Photo",
        "video": "Video",
        "audio": "Audio",
        "file": "File",
        "attach": "Attach",
        "saved_messages": "Saved Messages",
        "camera": "Camera",
        "location": "Location",
        "contact": "Contact",
        "poll": "Poll",
        "voice_message": "Voice message",
        "username": "Username",
        "display_name": "Display Name",
        "bio": "Bio",
        "phone": "Phone",
        "edit_profile": "Edit Profile",
        "change_avatar": "Change Photo",
        "privacy_security": "Privacy",
        "confidentiality": "Confidentiality",
        "chat_appearance": "Chat Appearance",
        "notification_settings": "Notifications",
        "language": "Language",
        "data_storage": "Data & Storage",
        "help": "Help",
        "about": "About",
        "logout": "Log Out",
        "show_online_status": "Show Online Status",
        "show_last_seen": "Show Last Seen",
        "read_receipts": "Read Receipts",
        "show_typing": "Typing Indicator",
        "two_step_verification": "Two-Step Verification",
        "enable": "Enable",
        "disable": "Disable",
        "blocked_users": "Blocked Users",
        "active_sessions": "Active Sessions",
        "theme": "Theme",
        "light": "Light",
        "dark": "Dark",
        "system": "System",
        "wallpaper": "Chat Wallpaper",
        "font_size": "Font Size",
        "message_corners": "Message Corners",
        "bubble_color": "Bubble Color",
        "notification_sound": "Notification Sound",
        "vibration": "Vibration",
        "message_preview": "Message Preview",
        "in_app_notifications": "In-App Notifications",
        "contacts": "Contacts",
        "add_contact": "Add Contact",
        "favorites": "Favorites",
        "no_chats": "No chats yet",
        "no_notifications": "No notifications",
        "no_contacts": "No contacts",
        "no_results": "No results",
        "loading": "Loading...",
        "error": "Error",
        "retry": "Retry",
        "select_members": "Select Members",
        "group_created": "Group created",
        "channel_created": "Channel created",
        "message_deleted": "Message deleted",
        "copied": "Copied",
        "pinned": "Pinned",
        "welcome": "Welcome to MQ!",
        "welcome_subtitle": "Fast and secure messenger",
        "calls": "Calls",
        "voice_call": "Voice Call",
        "video_call": "Video Call",
        "end_call": "End Call",
        "stories": "Stories",
        "pin_code": "PIN Code",
        "enter_pin": "Enter PIN",
        "confirm_pin": "Confirm PIN",
        "clear_chat": "Clear Chat",
        "auto_delete": "Auto-Delete",
        "encryption": "Encryption",
        "e2e_encrypted": "End-to-End Encrypted",
        "fingerprint_lock": "Fingerprint Lock",
        "public_group": "Public Group",
        "private_group": "Private Group",
        "slow_mode": "Slow Mode",
        "permissions": "Permissions",
        "send_media": "Send Media",
        "version": "Version",
    ]

    private init() {
        let saved = UserDefaults.standard.string(forKey: "mq_language")
        currentLanguage = saved ?? (Locale.current.language.languageCode?.identifier == "ru" ? "ru" : "en")
        loadStrings()
    }

    private func loadStrings() {
        strings = currentLanguage == "ru" ? ru : en
    }

    func string(for key: String) -> String {
        strings[key] ?? key
    }

    func toggleLanguage() {
        currentLanguage = currentLanguage == "ru" ? "en" : "ru"
    }
}

extension String {
    var localized: String {
        LocalizationManager.shared.string(for: self)
    }
}
